### ISSUE TITLE
result

### ISSUE THREAD

**Issue by LIUYAJINGUSTC** [IMLHF/SE_DCUNet#1]
Hi, could you tell me the result of this code for VoiceBank？I cannot get the result in the paper.

**Comment by IMLHF** [comment]
the article “Phase-Aware Speech Enhancement with Deep Complex U-Net” has retracted, see https://openreview.net/forum?id=SkeRTsAcYm
“”“”“”
Retracted from ICLR2019. 
ICLR 2019 Conference Paper850 Authors
28 Apr 2019ICLR 2019 Conference Paper850 Official CommentReaders:  Everyone
Comment: Dear readers, this is the announcement of the retraction of our paper "Phase-Aware Speech Enhancement with Deep Complex U-Net" from ICLR2019. 

First, we thank you for the interest in our work.

We are truly sorry, however, to inform that a significant error was found by ourselves in the experimental process of our paper “Phase-aware Speech Enhancement with Deep Complex U-Net”, which was accepted for ICLR2019. After careful examinations, we therefore have made a decision to retract the accepted paper.

To be more specific about the error, we found out that the training data path was accidentally set to the evaluation data path which means the reported numbers in the table are utterly wrong (possibly overfitted results).

Lastly, we sincerely apologize for the mistake we made and promise it will not happen again.

Best regards,
Authors
