### ISSUE TITLE
se_dataset.py

### ISSUE THREAD

**Issue by njusq** [IMLHF/SE_DCUNet#2]
Hi! Thank you for your code.
I tried to run your code with my own dataset, and found you changed line 96 in se_dataset.py from 
`input_mat[e, :inp.shape[0]] = inp`
to
` input_mat[e] = inp # no padding`

Is there anything special in your data so you wrote it like this?

**Comment by IMLHF** [comment]
i repeat the wav to a fixed length, instead of padding
